export default {
  SET_REQUEST: "CONTEXT/SET/REQUEST",
  SET_FAILURE: "CONTEXT/SET/FAILURE",
  SET_SUCCESS: "CONTEXT/SET/SUCCESS",
  STRIP_REQUEST: "CONTEXT/STRIP/REQUEST",
  STRIP_FAILURE: "CONTEXT/STRIP/FAILURE",
  STRIP_SUCCESS: "CONTEXT/STRIP/SUCCESS",
};
