export const INIT_WEB3_REQUEST = 'INIT_WEB3_REQUEST'
export const INIT_WEB3_FAILURE = 'INIT_WEB3_FAILURE'
export const INIT_WEB3_SUCCESS = 'INIT_WEB3_SUCCESS'

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST'
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'

export const RECEIVE_DEFAULT_ACCOUNT = 'RECEIVE_DEFAULT_ACCOUNT'
export const CHANGE_DEFAULT_ACCOUNT = 'CHANGE_DEFAULT_ACCOUNT'

export const INIT_CONTRACT_REQUEST = 'INIT_CONTRACT_REQUEST'
export const INIT_CONTRACT_FAILURE = 'INIT_CONTRACT_FAILURE'
export const INIT_CONTRACT_SUCCESS = 'INIT_CONTRACT_SUCCESS'
