export const WEB3 = {
  INIT_REQUEST: 'WEB3/INIT_REQUEST',
  INIT_FAILURE: 'WEB3/INIT_FAILURE',
  INIT_SUCCESS: 'WEB3/INIT_SUCCESS'
}

export const ACCOUNTS = {
  GET_REQUEST: 'ACCOUNTS/GET_REQUEST',
  GET_FAILURE: 'ACCOUNTS/GET_FAILURE',
  GET_SUCCESS: 'ACCOUNTS/GET_SUCCESS'
}

export const CONTRACT = {
  INIT_REQUEST: 'CONTRACT/INIT_REQUEST',
  INIT_FAILURE: 'CONTRACT/INIT_FAILURE',
  INIT_SUCCESS: 'CONTRACT/INIT_SUCCESS'
}
